#This query illustrates how to describe a resource which is identified
#by matching one of its properties. In this case a work is being identified
#using its ISBN-10 value.
# @title Describe via ISSN
# @author Leigh Dodds
# @see http://www.isbn.org/
# @tag book
# @tag isbn
# @endpoint http://bnb.data.bl.uk/sparql 
PREFIX bibo: <http://purl.org/ontology/bibo/> 
DESCRIBE ?uri WHERE {
  ?uri bibo:isbn10 "0261102214".
}

